import * as THREE from 'three';

export const WALK_PATH = new THREE.CatmullRomCurve3([
  new THREE.Vector3(0, 0, 65),
  new THREE.Vector3(0, 0, 25),
  new THREE.Vector3(-12, 0, 5),
  new THREE.Vector3(-36, 0, -22),
  new THREE.Vector3(-58, 0, -52),
  new THREE.Vector3(-60, 0, -85),
  new THREE.Vector3(-44, 0, -112),
  new THREE.Vector3(-10, 0, -130),
  new THREE.Vector3(24, 0, -148),
  new THREE.Vector3(50, 0, -172),
  new THREE.Vector3(48, 0, -200),
  new THREE.Vector3(20, 0, -222),
  new THREE.Vector3(0, 0, -242),
]);

export enum AnimationsName {
  A_TPose = "A_TPose",
  Crouch_Fwd_Loop = "Crouch_Fwd_Loop",
  Crouch_Idle_Loop = "Crouch_Idle_Loop",
  Dance_Loop = "Dance_Loop",
  Death01 = "Death01",
  Driving_Loop = "Driving_Loop",
  Fixing_Kneeling = "Fixing_Kneeling",
  Hit_Chest = "Hit_Chest",
  Hit_Head = "Hit_Head",
  Idle_Loop = "Idle_Loop",
  Idle_Talking_Loop = "Idle_Talking_Loop",
  Idle_Torch_Loop = "Idle_Torch_Loop",
  Interact = "Interact",
  Jog_Fwd_Loop = "Jog_Fwd_Loop",
  Jump_Land = "Jump_Land",
  Jump_Loop = "Jump_Loop",
  Jump_Start = "Jump_Start",
  PickUp_Table = "PickUp_Table",
  Pistol_Aim_Down = "Pistol_Aim_Down",
  Pistol_Aim_Neutral = "Pistol_Aim_Neutral",
  Pistol_Aim_Up = "Pistol_Aim_Up",
  Pistol_Idle_Loop = "Pistol_Idle_Loop",
  Pistol_Reload = "Pistol_Reload",
  Pistol_Shoot = "Pistol_Shoot",
  Punch_Cross = "Punch_Cross",
  Punch_Jab = "Punch_Jab",
  Push_Loop = "Push_Loop",
  Roll = "Roll",
  Roll_RM = "Roll_RM",
  Sitting_Enter = "Sitting_Enter",
  Sitting_Exit = "Sitting_Exit",
  Sitting_Idle_Loop = "Sitting_Idle_Loop",
  Sitting_Talking_Loop = "Sitting_Talking_Loop",
  Spell_Simple_Enter = "Spell_Simple_Enter",
  Spell_Simple_Exit = "Spell_Simple_Exit",
  Spell_Simple_Idle_Loop = "Spell_Simple_Idle_Loop",
  Spell_Simple_Shoot = "Spell_Simple_Shoot",
  Sprint_Loop = "Sprint_Loop",
  Swim_Fwd_Loop = "Swim_Fwd_Loop",
  Swim_Idle_Loop = "Swim_Idle_Loop",
  Sword_Attack = "Sword_Attack",
  Sword_Attack_RM = "Sword_Attack_RM",
  Sword_Idle = "Sword_Idle",
  Walk_Formal_Loop = "Walk_Formal_Loop",
  Walk_Loop = "Walk_Loop",
}